[package]
name = "m2m-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
rust-bert = "0.23.0"
rust_tokenizers = "8.1.1"
tch = { version = "0.17.0", features = ["download-libtorch"] }
